---
- name: Set Jenkins key
  sudo: no
  shell: wget -q -O - https://jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -

- name: Set Jenkins binary
  sudo: yes
  shell: sh -c 'echo deb http://pkg.jenkins-ci.org/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install Jenkins
  sudo: yes
  apt: pkg=jenkins state=latest

- name: Wait until Jenkins port opens
  wait_for:
    port: 80
    delay: 60

- name: Create initialization scripts directory
  file: path=/var/lib/jenkins/init.groovy.d
        state=directory
        owner=jenkins
        group=jenkins
        mode=0775

- name: Configure JVM Arguments
  lineinfile:
    dest: /etc/default/jenkins
    regexp: '^JAVA_ARGS='
    line: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false -Djavax.net.ssl.trustStore=$JAVA_HOME/jre/lib/security/cacerts -Djavax.net.ssl.trustAnchors=$JAVA_HOME/jre/lib/security/cacerts"'

- name: Install plugin
  jenkins_plugin:
    name: build-pipeline-plugin


- name: Add initialization script to setup basic security
  template: src=security.groovy.j2
            dest=/var/lib/jenkins/init.groovy.d/security.groovy
  notify: Restart jenkins


