---
- name: Set Jenkins key
  sudo: no
  shell: wget -q -O - https://jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -

- name: Set Jenkins binary
  sudo: yes
  shell: sh -c 'echo deb http://pkg.jenkins-ci.org/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install Jenkins
  sudo: yes
  apt: pkg=jenkins state=latest
