---
- hosts: all
  sudo: true
  vars_files:
    - vars/all.yml
  roles:
    - server
    - vagrant_local
    - nginx
    - ant
    - ivy
    - spring-boot-antlib
    - java
    - docker
    - jenkins
    - app
