---
server:
    install: '1'
    packages: [vim, git]
    timezone: Europe/Brussels
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: jenkins, ip: 192.168.33.12, memory: '1024', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
nginx:
    install: '1'
    docroot: /vagrant
    servername: jenkins
jenkins:
    admin_username: admin
    admin_password: foobar    
nexus3:
    version: 3.0.2-02
    package: nexus-3.0.2-02-unix.tar.gz
    group: 'nexus'
    user: 'nexus'
    shell: '/bin/bash'
    installation_dir: '/usr/share'
docker:
    package: "docker-engine"
    package_state: present

# Docker Compose options.
    install_compose: true
    compose_version: "1.16.1"
    compose_path: /usr/local/bin/docker-compose

# Used only for Debian/Ubuntu. Switch 'stable' to 'edge' if needed.
    apt_release_channel: stable
    apt_repository: "deb https://apt.dockerproject.org/repo ubuntu-trusty main"
ant:
    home: /usr/local/apache-ant
    version: 1.9.7
    versions_dir: /usr/local/apache-ant-versions

ivy:
    version: 2.4.0
