---
- name: Set Jenkins key
  sudo: no
  shell: wget -q -O - https://jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -

- name: Set Jenkins binary
  sudo: yes
  shell: sh -c 'echo deb http://pkg.jenkins-ci.org/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install Jenkins
  sudo: yes
  apt: pkg=jenkins state=latest

- name: Wait until Jenkins port opens
  wait_for:
    port: 8080
    delay: 60

- name: Create initialization scripts directory
  file: path=/var/lib/jenkins/init.groovy.d
        state=directory
        owner=jenkins
        group=jenkins
        mode=0775

- name: Configure JVM Arguments
  lineinfile:
    dest: /etc/default/jenkins
    regexp: '^JAVA_ARGS='
#    line: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false -Djavax.net.ssl.trustStore=$JAVA_HOME/jre/lib/security/cacerts -Djavax.net.ssl.trustAnchors=$JAVA_HOME/jre/lib/security/cacerts"'
    line: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'


- name: Add initialization script to setup basic security
  template: src=security.groovy.j2
            dest=/var/lib/jenkins/init.groovy.d/security.groovy

- name: Adding jenkins to docker group 
  user: name=jenkins
        groups=sudo
        append=yes

- name:  Restart jenkins
  service: name=jenkins enabled=yes state=restarted

- name: Wait for Jenkins to start to install plugins
  uri:
    url: http://192.168.33.12:8080
    status_code: 200
    timeout: 5
    user: admin
    password: foobar
    force_basic_auth: yes
  register: jenkins_service_status
  # Keep trying for 5 mins in 5 sec intervals
  retries: 60
  delay: 5
  until: >
     'status' in jenkins_service_status and
     jenkins_service_status['status'] == 200

- name: Install pipeline plugin
  jenkins_plugin:
#    name: build-pipeline-plugin
    name: workflow-aggregator
    url_username: admin
    url_password: foobar
    updates_url: http://pkg.jenkins.io/
    timeout: 180

- name: Install build  pipeline plugin
  jenkins_plugin:
    name: build-pipeline-plugin
    url_username: admin
    url_password: foobar
    updates_url: http://pkg.jenkins.io/
    timeout: 180


- name: Install multibranch pipeline plugin
  jenkins_plugin:
#    name: build-pipeline-plugin
    name: workflow-multibranch
    url_username: admin
    url_password: foobar
    updates_url: http://pkg.jenkins.io/
    timeout: 180

- name: Install git  plugin
  jenkins_plugin:
    name: git
    url_username: admin
    url_password: foobar
    updates_url: http://pkg.jenkins.io/
    timeout: 180

- name: Install gitlab  plugin
  jenkins_plugin:
    name: gitlab-plugin
    url_username: admin
    url_password: foobar
    updates_url: http://pkg.jenkins.io/
    timeout: 180

- name: Install declarative pipeline plugin
  jenkins_plugin:
    name: pipeline-model-definition
    url_username: admin
    url_password: foobar
    updates_url: http://pkg.jenkins.io/
    timeout: 180

- name: Install pipeline stage view plugin
  jenkins_plugin:
    name: pipeline-stage-view
    url_username: admin
    url_password: foobar
    updates_url: http://pkg.jenkins.io/
    timeout: 180

- name: Install Docker build step plugin
  jenkins_plugin:
    name: docker-build-step
    url_username: admin
    url_password: foobar
    updates_url: http://pkg.jenkins.io/
    timeout: 180

- name: Install Docker slaves plugin
  jenkins_plugin:
    name: docker-slaves
    url_username: admin
    url_password: foobar
    updates_url: http://pkg.jenkins.io/
    timeout: 180

- name: Install Docker  plugin
  jenkins_plugin:
    name: docker-plugin
    url_username: admin
    url_password: foobar 
    updates_url: http://pkg.jenkins.io/
    timeout: 180

- name: Install Docker common plugin
  jenkins_plugin:
    name: docker-commons
    url_username: admin
    url_password: foobar
    updates_url: http://pkg.jenkins.io/
    timeout: 180

- name: Install jcloud plugin
  jenkins_plugin:
    name: jclouds-jenkins
    url_username: admin
    url_password: foobar
    updates_url: http://pkg.jenkins.io/
    timeout: 180

- name: Install ssh agents plugin
  jenkins_plugin:
    name: ssh-slaves
    url_username: admin 
    url_password: foobar
    updates_url: http://pkg.jenkins.io/
    timeout: 180

- name: Install slave setup plugin
  jenkins_plugin:
    name: slave-setup
    url_username: admin
    url_password: foobar
    updates_url: http://pkg.jenkins.io/
    timeout: 180

- name: Install ansi clour plugin
  jenkins_plugin:
    name: ansicolor
    url_username: admin
    url_password: foobar
    updates_url: http://pkg.jenkins.io/
    timeout: 180



- name:  Restart jenkins after plugins
  service: name=jenkins enabled=yes state=restarted

