pipeline {
//     agent { label 'docker-agent' }
     agent any
     stages {
          stage('Checkout') {
               steps {
                    git url: 'http://192.168.33.11/root/pipeline-net'
               }
          }
          stage('Second Stage') {
               steps {
                    echo 'Step 2. Second time Hello'
                    echo 'Step 3. Third time Hello'
               }
          }
     }
}
