---
- name: check which version is installed
  shell: "ls -1v {{ant.home}}/lib/ivy-*.jar | tail -1 | gawk 'match($0,/ivy-(.+)\\.jar/, group) {print group[1]}'"
  changed_when: false
  failed_when: false
  check_mode: no
  register: current_version

- name: check if the new version should be installed or not
  set_fact:
    install_ivy: "{{ (current_version.rc > 0) or (current_version.stderr_lines | length > 0) or (current_version.stdout | version_compare(ivy.version, '<'))}}"

- block:
  - name: download
    get_url:
      url: "http://archive.apache.org/dist/ant/ivy/{{ ivy.version }}/apache-ivy-{{ ivy.version }}-bin.tar.gz"
      dest: "/tmp/apache-ivy-{{ivy.version}}-bin.tar.gz"
    when: install_ivy

  - name: extract ivy-{{ivy.version}}.jar to {{ant.home}}/lib
    unarchive: 
      copy: False
      src: "/tmp/apache-ivy-{{ivy.version}}-bin.tar.gz"
      dest: "{{ant.home}}/lib"
      extra_opts:
        - "--strip-components=1"
        - "apache-ivy-{{ivy.version}}/ivy-{{ivy.version}}.jar"
    when: install_ivy

  always:
  - name: delete downloaded files
    file:
      state: absent
      path: "/tmp/apache-ivy-{{ivy.version}}-bin.tar.gz"
    when: install_ivy
